[phases.setup]
aptPkgs = [
    "libgl1",
    "libglib2.0-0",
    "libxcb1",
    "libx11-xcb1",
    "libxrender1",
    "libxi6",
    "libxext6"
]

[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]